# Sklearn Practice

[link to the tutorial](https://elitedatascience.com/python-machine-learning-tutorial-scikit-learn)

## Import libraries and modules

In [40]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.ensemble import RandomForestRegressor
# 
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.externals import joblib

 ## Load red wine data.

In [38]:
# Load data from a remote URL
dataset_url = 'http://mlr.cs.umass.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv'
data = pd.read_csv(dataset_url)
print (data.head())

  fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"
0   7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5                                                                                                                     
1   7.8;0.88;0;2.6;0.098;25;67;0.9968;3.2;0.68;9.8;5                                                                                                                     
2  7.8;0.76;0.04;2.3;0.092;15;54;0.997;3.26;0.65;...                                                                                                                     
3  11.2;0.28;0.56;1.9;0.075;17;60;0.998;3.16;0.58...                                                                                                                     
4   7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5                                                                                                  

In [ ]:
# Read CSV with semicolon separator as the one above seems quite messy
data = pd.read_csv(dataset_url, sep=';')
print (data.head())

In [ ]:
# Looking at the shape
print (data.shape)

In [ ]:
# Summary statistics
print (data.describe())

## Split data into training and test sets

In [ ]:
# Separate target from training features
y = data.quality
X = data.drop('quality', axis=1)

In [ ]:
# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123, stratify=y)


In [ ]:
print (X_train.shape)
print(X_test.shape)
print(X.shape)

In [ ]:
# Fitting the Transformer API
scaler = preprocessing.StandardScaler().fit(X_train)

# Applying transformer to training data
X_train_scaled = scaler.transform(X_train)

print("Training Data")
print (X_train_scaled.mean(axis=0))
# [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
print (X_train_scaled.std(axis=0))
# [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]



# Applying transformer to test data
X_test_scaled = scaler.transform(X_test)

print("Test Data") 
print (X_test_scaled.mean(axis=0))
# [ 0.02776704  0.02592492 -0.03078587 -0.03137977 -0.00471876 -0.04413827
#  -0.02414174 -0.00293273 -0.00467444 -0.10894663  0.01043391]
 
print (X_test_scaled.std(axis=0))
# [ 1.02160495  1.00135689  0.97456598  0.91099054  0.86716698  0.94193125
#  1.03673213  1.03145119  0.95734849  0.83829505  1.0286218 ]

## Declare data preprocessing steps

In practice, when we set up the cross-validation pipeline, we won't even need to manually fit the Transformer API. Instead, we'll simply declare the class object, like so:

In [ ]:
# Pipeline with preprocessing and model
pipeline = make_pipeline(preprocessing.StandardScaler(), 
                         RandomForestRegressor(n_estimators=100))

print (pipeline.get_params())

## Cross Validation

In [64]:
# Declare hyperparameters to tune
hyperparameters = { 'randomforestregressor__max_features' : ['auto', 'sqrt', 'log2'],
                    'randomforestregressor__max_depth': [None, 5, 3, 1]
                  }

# Sklearn cross-validation with pipeline
clf = GridSearchCV(pipeline, hyperparameters, cv=10)
 
# Fit and tune model
clf.fit(X_train, y_train)

# best set of parameters 
print (clf.best_params_)

# Confirm model will be retrained
print (clf.refit)

{'randomforestregressor__max_depth': None, 'randomforestregressor__max_features': 'sqrt'}
True


## Evaluate model pipeline on test data

In [65]:
# Predict a new set of data
y_pred = clf.predict(X_test)


print (r2_score(y_test, y_pred))
# 0.45044082571584243
 
print (mean_squared_error(y_test, y_pred))
# 0.35461593750000003

## Saving and loading the model for future use

In [67]:
# Save model to a .pkl file
joblib.dump(clf, 'rf_regressor.pkl')

# Load model from .pkl file
clf2 = joblib.load('rf_regressor.pkl')
 
# Predict data set using loaded model
clf2.predict(X_test)


array([6.41, 5.7 , 5.02, 5.53, 6.27, 5.65, 4.95, 4.83, 5.01, 6.1 , 5.33,
       5.67, 5.79, 5.1 , 5.71, 5.67, 6.44, 5.71, 5.75, 7.  , 5.49, 5.66,
       5.04, 5.95, 5.94, 5.04, 5.56, 5.21, 5.9 , 5.93, 5.87, 6.44, 5.99,
       5.04, 4.99, 5.88, 5.02, 6.11, 4.99, 5.89, 4.96, 5.98, 6.63, 5.08,
       6.2 , 5.37, 5.55, 5.54, 5.13, 6.43, 6.12, 5.22, 5.74, 5.17, 5.56,
       5.69, 5.37, 5.41, 4.98, 5.25, 5.3 , 5.07, 5.05, 5.79, 5.99, 5.41,
       6.34, 5.06, 5.15, 6.67, 5.77, 5.83, 5.05, 5.02, 5.42, 6.05, 5.15,
       5.08, 5.2 , 5.22, 6.36, 5.58, 6.21, 6.42, 5.16, 5.99, 6.38, 6.31,
       5.71, 5.69, 6.01, 5.29, 6.36, 5.82, 5.73, 5.81, 6.67, 6.74, 5.54,
       6.82, 5.11, 5.4 , 5.18, 6.48, 5.13, 4.63, 5.68, 5.05, 5.58, 5.91,
       5.89, 5.4 , 5.97, 5.34, 5.34, 5.22, 5.93, 5.09, 5.04, 6.2 , 5.91,
       5.17, 5.81, 6.14, 5.22, 5.4 , 5.2 , 6.03, 5.61, 5.39, 5.69, 6.38,
       5.17, 5.32, 5.04, 6.35, 4.99, 5.16, 6.8 , 5.57, 5.14, 5.1 , 5.53,
       6.16, 5.33, 5.37, 5.11, 6.44, 5.87, 5.09, 5.